baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "XCity Lin" # the base hostname & protocol for your site.
title: "XCity Lin 林轩城"

paginate: 10 #articles per page
paginate_path: /blog/page:num #makes pagination working

baseurl: "http://www.xcity.site/"

#contacts
# git: "https://github.com/railsr"  #your github url here.
# stackoverflow: "http://stackoverflow.com/users/1231365/railsr" #Add your stackoverflow url here.
# twitter: "https://twitter.com/railsr7"  #Add your twitter url here.

#disqus comment
disqus:
    shortname: "test" #your disqus comment short name

#google analytics
google:
    tracking-id: "" #your tracking id here

gems:
  - jekyll-sitemap
  - jekyll-paginate

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"

permalink: /posts/:title

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
